name: CI build & deploy to Azure App Service (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use cache only if a lockfile exists
      - name: Setup Node 18 (with cache if lockfile)
        if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json','**/yarn.lock') != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
            **/npm-shrinkwrap.json
            **/yarn.lock

      # Fallback: setup without cache
      - name: Setup Node 18 (no cache)
        if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json','**/yarn.lock') == '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Prefer deterministic install when lockfile exists
      - name: Install dependencies (npm ci)
        if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json') != '' }}
        run: npm ci

      - name: Install dependencies (npm install)
        if: ${{ hashFiles('**/package-lock.json','**/npm-shrinkwrap.json') == '' }}
        run: npm install

      - name: Build
        run: npm run build

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: commandcentreit
          package: .
