name: CI build & deploy to Azure App Service (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write      # required for OIDC
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B1B3251BFBF42E48A2390AAECF977FD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A1273148DC76455D8F532C7C8E20419F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_123B8D70439C4829AE96566A6FD33504 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: commandcentreit
          package: .
